name: Build:ubuntu.64
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup pyinstaller
        run: pip install pyinstaller
      - name: Build
        run: pyinstaller "MSMS.py" --distpath "build\ubuntu-64\latest\dist\" --workpath "build\ubuntu-64\latest\build\" -y
      - name : Pack
        run: |
          zip -r MSMS-ubuntu.64-latest-full.zip -i build\ubuntu-64\latest\
      - name: Send
        run: mail -s "MSMS project ubuntu-x64 build" liuzhiyu@liuzhiyu.onmicrosoft.com -A "build\ubuntu-64\latest\MSMS-ubuntu.64-latest-full.zip" <<< "Please read."
